### ISSUE TITLE
dependency Problems

### ISSUE THREAD

**Issue by Lukas2019** [bennyboer/bbb_app#186]
**Describe the bug**
Problem withe intl ^0.16.1 dependency 
`Running "flutter pub get" in bbb_app-main...                    
Because bbb_app depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.

So, because bbb_app depends on intl ^0.16.1, version solving failed.
pub get failed (1; So, because bbb_app depends on intl ^0.16.1, version solving failed.)
exit code 1`

**To Reproduce**
Wen Trying to run the error appears 

**Expected behavior**
The app should start.

**Smartphone (please complete the following information):**
Android & Web

**Operating System:**
Arch Linux

**Additional context**
I removed the version Number in "pubspec.yaml" then it worked ( do not know if this is a good fix (newbe))

**Comment by bennyboer** [comment]
Can you add your Flutter SDK version please. Maybe you're using a newer one than we do :)

**Comment by Faisalkc4u** [comment]
Hi @bennyboer, I am facing the same issue I am using flutter 2.0.6. Could you let me know which flutter version you are using or this project ? Thanks

**Comment by Faisalkc4u** [comment]
I updated my pubspec.yml file to this

```
version: 0.2.6+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_webrtc: ^0.6.5
  shared_preferences:
  shared_preferences_macos:
  shared_preferences_web:
  http: ^0.13.3
  html: ^0.15.0
  day_night_switcher: ^0.2.0+1
  provider: ^5.0.0
  intl: ^0.17.0
  sprintf: ^6.0.0
  flutter_svg: ^0.22.0
  sip_ua: #^0.3.5
    git: https://github.com/flutter-webrtc/dart-sip-ua.git
  flutter_markdown: ^0.6.2
  uni_links: ^0.5.1
  flutter_foreground_plugin: ^0.8.0
  logger: ^1.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1 
  url_launcher: ^6.0.9
dependency_overrides:
  logger: ^0.9.0
  flutter_webrtc: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_math: any
```


And this is working for me, also I use flutter v2.0.6 stable

```
Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (10 weeks ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3

```
